package com.android.billingclient.api;

import com.android.billingclient.api.BillingResult;

/* JADX INFO: compiled from: r8-map-id-11d7710e1e89b9f435e4c01ffffd6a5bc78c9d6db2bbad6c6777697ebd4119c9 */
/* JADX INFO: loaded from: classes.dex */
public final class zzcp {
    public static final BillingResult zzA;
    public static final BillingResult zzB;
    public static final BillingResult zzC;
    public static final BillingResult zzD;
    public static final BillingResult zzE;
    public static final BillingResult zzF;
    public static final /* synthetic */ int zzG = 0;
    public static final BillingResult zza;
    public static final BillingResult zzb;
    public static final BillingResult zzc;
    public static final BillingResult zzd;
    public static final BillingResult zze;
    public static final BillingResult zzf;
    public static final BillingResult zzg;
    public static final BillingResult zzh;
    public static final BillingResult zzi;
    public static final BillingResult zzj;
    public static final BillingResult zzk;
    public static final BillingResult zzl;
    public static final BillingResult zzm;
    public static final BillingResult zzn;
    public static final BillingResult zzo;
    public static final BillingResult zzp;
    public static final BillingResult zzq;
    public static final BillingResult zzr;
    public static final BillingResult zzs;
    public static final BillingResult zzt;
    public static final BillingResult zzu;
    public static final BillingResult zzv;
    public static final BillingResult zzw;
    public static final BillingResult zzx;
    public static final BillingResult zzy;
    public static final BillingResult zzz;

    static {
        BillingResult.Builder builderNewBuilder = BillingResult.newBuilder();
        builderNewBuilder.zza = 3;
        builderNewBuilder.zzc = "Google Play In-app Billing API version is less than 3";
        builderNewBuilder.build();
        BillingResult.Builder builderNewBuilder2 = BillingResult.newBuilder();
        builderNewBuilder2.zza = 3;
        builderNewBuilder2.zzc = "Google Play In-app Billing API version is less than 9";
        zza = builderNewBuilder2.build();
        BillingResult.Builder builderNewBuilder3 = BillingResult.newBuilder();
        builderNewBuilder3.zza = 3;
        builderNewBuilder3.zzc = "Billing service unavailable on device.";
        zzb = builderNewBuilder3.build();
        BillingResult.Builder builderNewBuilder4 = BillingResult.newBuilder();
        builderNewBuilder4.zza = 2;
        builderNewBuilder4.zzc = "Billing service unavailable on device.";
        zzc = builderNewBuilder4.build();
        BillingResult.Builder builderNewBuilder5 = BillingResult.newBuilder();
        builderNewBuilder5.zza = 5;
        builderNewBuilder5.zzc = "Client is already in the process of connecting to billing service.";
        zzd = builderNewBuilder5.build();
        BillingResult.Builder builderNewBuilder6 = BillingResult.newBuilder();
        builderNewBuilder6.zza = 5;
        builderNewBuilder6.zzc = "The list of SKUs can't be empty.";
        builderNewBuilder6.build();
        BillingResult.Builder builderNewBuilder7 = BillingResult.newBuilder();
        builderNewBuilder7.zza = 5;
        builderNewBuilder7.zzc = "SKU type can't be empty.";
        builderNewBuilder7.build();
        BillingResult.Builder builderNewBuilder8 = BillingResult.newBuilder();
        builderNewBuilder8.zza = 5;
        builderNewBuilder8.zzc = "Product type can't be empty.";
        zze = builderNewBuilder8.build();
        BillingResult.Builder builderNewBuilder9 = BillingResult.newBuilder();
        builderNewBuilder9.zza = -2;
        builderNewBuilder9.zzc = "Client does not support extra params.";
        zzf = builderNewBuilder9.build();
        BillingResult.Builder builderNewBuilder10 = BillingResult.newBuilder();
        builderNewBuilder10.zza = 5;
        builderNewBuilder10.zzc = "Invalid purchase token.";
        zzg = builderNewBuilder10.build();
        BillingResult.Builder builderNewBuilder11 = BillingResult.newBuilder();
        builderNewBuilder11.zza = 6;
        builderNewBuilder11.zzc = "An internal error occurred.";
        zzh = builderNewBuilder11.build();
        BillingResult.Builder builderNewBuilder12 = BillingResult.newBuilder();
        builderNewBuilder12.zza = 5;
        builderNewBuilder12.zzc = "SKU can't be null.";
        builderNewBuilder12.build();
        BillingResult.Builder builderNewBuilder13 = BillingResult.newBuilder();
        builderNewBuilder13.zza = 0;
        zzi = builderNewBuilder13.build();
        BillingResult.Builder builderNewBuilder14 = BillingResult.newBuilder();
        builderNewBuilder14.zza = -1;
        builderNewBuilder14.zzc = "Service connection is disconnected.";
        zzj = builderNewBuilder14.build();
        BillingResult.Builder builderNewBuilder15 = BillingResult.newBuilder();
        builderNewBuilder15.zza = 2;
        builderNewBuilder15.zzc = "Timeout communicating with service.";
        zzk = builderNewBuilder15.build();
        BillingResult.Builder builderNewBuilder16 = BillingResult.newBuilder();
        builderNewBuilder16.zza = -2;
        builderNewBuilder16.zzc = "Client does not support subscriptions.";
        zzl = builderNewBuilder16.build();
        BillingResult.Builder builderNewBuilder17 = BillingResult.newBuilder();
        builderNewBuilder17.zza = -2;
        builderNewBuilder17.zzc = "Client does not support subscriptions update.";
        zzm = builderNewBuilder17.build();
        BillingResult.Builder builderNewBuilder18 = BillingResult.newBuilder();
        builderNewBuilder18.zza = -2;
        builderNewBuilder18.zzc = "Client does not support get purchase history.";
        builderNewBuilder18.build();
        BillingResult.Builder builderNewBuilder19 = BillingResult.newBuilder();
        builderNewBuilder19.zza = -2;
        builderNewBuilder19.zzc = "Client does not support price change confirmation.";
        zzn = builderNewBuilder19.build();
        BillingResult.Builder builderNewBuilder20 = BillingResult.newBuilder();
        builderNewBuilder20.zza = -2;
        builderNewBuilder20.zzc = "Play Store version installed does not support cross selling products.";
        zzo = builderNewBuilder20.build();
        BillingResult.Builder builderNewBuilder21 = BillingResult.newBuilder();
        builderNewBuilder21.zza = -2;
        builderNewBuilder21.zzc = "Client does not support multi-item purchases.";
        zzp = builderNewBuilder21.build();
        BillingResult.Builder builderNewBuilder22 = BillingResult.newBuilder();
        builderNewBuilder22.zza = -2;
        builderNewBuilder22.zzc = "Client does not support offer_id_token.";
        zzq = builderNewBuilder22.build();
        BillingResult.Builder builderNewBuilder23 = BillingResult.newBuilder();
        builderNewBuilder23.zza = -2;
        builderNewBuilder23.zzc = "Client does not support ProductDetails.";
        zzr = builderNewBuilder23.build();
        BillingResult.Builder builderNewBuilder24 = BillingResult.newBuilder();
        builderNewBuilder24.zza = -2;
        builderNewBuilder24.zzc = "Client does not support in-app messages.";
        zzs = builderNewBuilder24.build();
        BillingResult.Builder builderNewBuilder25 = BillingResult.newBuilder();
        builderNewBuilder25.zza = -2;
        builderNewBuilder25.zzc = "Client does not support user choice billing.";
        builderNewBuilder25.build();
        BillingResult.Builder builderNewBuilder26 = BillingResult.newBuilder();
        builderNewBuilder26.zza = -2;
        builderNewBuilder26.zzc = "Play Store version installed does not support external offer.";
        zzt = builderNewBuilder26.build();
        BillingResult.Builder builderNewBuilder27 = BillingResult.newBuilder();
        builderNewBuilder27.zza = -2;
        builderNewBuilder27.zzc = "Play Store version installed does not support multi-item purchases with season pass in one cart.";
        zzu = builderNewBuilder27.build();
        BillingResult.Builder builderNewBuilder28 = BillingResult.newBuilder();
        builderNewBuilder28.zza = -2;
        builderNewBuilder28.zzc = "Play Store version installed does not support querying AutoPay plan purchase.";
        zzv = builderNewBuilder28.build();
        BillingResult.Builder builderNewBuilder29 = BillingResult.newBuilder();
        builderNewBuilder29.zza = -2;
        builderNewBuilder29.zzc = "Play Store version installed does not support including suspended subscriptions.";
        zzw = builderNewBuilder29.build();
        BillingResult.Builder builderNewBuilder30 = BillingResult.newBuilder();
        builderNewBuilder30.zza = 5;
        builderNewBuilder30.zzc = "Unknown feature";
        zzx = builderNewBuilder30.build();
        BillingResult.Builder builderNewBuilder31 = BillingResult.newBuilder();
        builderNewBuilder31.zza = -2;
        builderNewBuilder31.zzc = "Play Store version installed does not support get billing config.";
        zzy = builderNewBuilder31.build();
        BillingResult.Builder builderNewBuilder32 = BillingResult.newBuilder();
        builderNewBuilder32.zza = -2;
        builderNewBuilder32.zzc = "Query product details with serialized docid is not supported.";
        zzz = builderNewBuilder32.build();
        BillingResult.Builder builderNewBuilder33 = BillingResult.newBuilder();
        builderNewBuilder33.zza = -2;
        builderNewBuilder33.zzc = "Play Store version installed does not support launching external offer flow.";
        zzA = builderNewBuilder33.build();
        BillingResult.Builder builderNewBuilder34 = BillingResult.newBuilder();
        builderNewBuilder34.zza = 4;
        builderNewBuilder34.zzc = "Item is unavailable for purchase.";
        zzB = builderNewBuilder34.build();
        BillingResult.Builder builderNewBuilder35 = BillingResult.newBuilder();
        builderNewBuilder35.zza = -2;
        builderNewBuilder35.zzc = "Query product details with developer specified account is not supported.";
        zzC = builderNewBuilder35.build();
        BillingResult.Builder builderNewBuilder36 = BillingResult.newBuilder();
        builderNewBuilder36.zza = -2;
        builderNewBuilder36.zzc = "Play Store version installed does not support alternative billing only.";
        zzD = builderNewBuilder36.build();
        BillingResult.Builder builderNewBuilder37 = BillingResult.newBuilder();
        builderNewBuilder37.zza = 5;
        builderNewBuilder37.zzc = "To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.";
        zzE = builderNewBuilder37.build();
        BillingResult.Builder builderNewBuilder38 = BillingResult.newBuilder();
        builderNewBuilder38.zza = 6;
        builderNewBuilder38.zzc = "An error occurred while retrieving billing override.";
        zzF = builderNewBuilder38.build();
        BillingResult.Builder builderNewBuilder39 = BillingResult.newBuilder();
        builderNewBuilder39.zza = -2;
        builderNewBuilder39.zzc = "Play Store version installed does not support the provided billing program.";
        builderNewBuilder39.build();
    }

    public static BillingResult zza(int i, String str) {
        BillingResult.Builder builderNewBuilder = BillingResult.newBuilder();
        builderNewBuilder.zza = i;
        builderNewBuilder.zzc = str;
        return builderNewBuilder.build();
    }
}
