version=8.0.0-billing-eap-cross-sell-per-transaction-offer-eap01
client=billing-eap-cross-sell-per-transaction-offer
billing-eap-cross-sell-per-transaction-offer_client=8.0.0-billing-eap-cross-sell-per-transaction-offer-eap01
